apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          #image: bitnami/redis
          image: redis
          command:
          - "redis-server"
          - "--appendonly"
          - "yes"
          - "--requirepass"
          - "redis"
          #env:
          #- name: REDIS_PASSWORD
          #  value: redis
          ports:
            - containerPort: 6379
          volumeMounts:
          - name: redisdata
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redisdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
